### ISSUE TITLE
Support Pydantic v2

### ISSUE THREAD

**Issue by srhinos** [getzep/zep-python#58]
[Pydantic has gone live with their new version](https://docs.pydantic.dev/2.0/blog/pydantic-v2-final/)

Being that its production ready and as suggested by Pydantic's [README](https://github.com/pydantic/pydantic):

> Pydantic V2 also ships with the latest version of Pydantic V1 built in so that you can incrementally upgrade your code base and projects: from pydantic import v1 as pydantic_v1.

It should be safe to upgrade and allow folks using poetry (like me) to resolve dependancies in a way that unblocks upgrading to Pydantic v2, FastAPI v0.100.0, etc

**Comment by danielchalef** [comment]
I'd like to do so, but as you've noted, Langchain requires:

pydantic = "^1"

As soon as Langchain supports pydantic v2, I'd be happy to upgrade.

**Comment by mac-ema** [comment]
Just as a note, zep is a dependency in langchain so until zep upgrades, langchain won’t be able to too 😂

I’m not sure which side is “wrong” or “right” or if there is one or the other but there might be a case where pydantic will have to be unpinned in one repo before the other can upgrade and then the first to unpin will then upgrade.

**Comment by danielchalef** [comment]
I've cut a PR with pydantic v1 & v2 support. I'd like to see it tested a little more before pushing a release.

**Comment by danielchalef** [comment]
As y'all may have noticed from the merged #60 PR, I've released v1.1.0a1 with Pydantic v2 support via v1 compatibility. https://pypi.org/project/zep-python/1.1.0a0/

install using:
```
pip install --pre zep-python
```

Let me know how it works out for you!

**Comment by danielchalef** [comment]
In `pre`. Shipping next week.
