### ISSUE TITLE
About the Rest API

### ISSUE THREAD

**Issue by JaydenCS** [getzep/zep-python#59]
Title: Error 400 when adding a new memory using REST API

Description:
I have been working with the API to create a session-based memory in my application. I've implemented basic GET and DELETE operations for memory, and they seem to be working properly. However, I'm encountering an Error 400 when trying to add a new memory using the POST method.

I've tried various approaches to pass the Memory object, including using the zep-python library, custom JSON, and other methods, but none of them seem to work. The API documentation lacks examples for the REST API part, making it difficult to troubleshoot the issue.

Steps to Reproduce:

Perform a POST request to add a new memory using the REST API.
Include the necessary parameters in the request (e.g., session ID, memory data).
Observe the Error 400 response.
Expected Behavior:
The POST request should add a new memory to the session without any errors.

Additional Information:

I have successfully used the GET and DELETE methods for memory, which suggests that the authentication and basic functionality of the API are working as expected.
The issue seems to be specific to the POST method when adding a new memory.

Note:
The API documentation lacks clear examples for the REST API part, especially when it comes to the POST method for adding a new memory. This makes it challenging to understand the correct format and parameters required for the request. It would be highly beneficial to include detailed examples in the documentation to help developers use the API effectively.

**Comment by danielchalef** [comment]
Swagger docs may be found in the Zep repo: https://github.com/getzep/zep/tree/main/docs

You should be able to render the UI for the swagger file using an IDE such as VS Code or PyCharm and point it to your Zep server, allowing you to use the "Try it out" functionality.

We also have a Swagger UI for Zep available here: https://getzep.github.io/zep/

Both of the above provide example payloads based on Zep's models.

**Comment by JaydenCS** [comment]
Got it ! Thank you so much for the fast response.
